server:
  port: 9091
spring:
  application:
    name: microservice-custom-movie
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9051/eureka/
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
